.TH RUN-KORUX-TESTS "1" "July 2025" "run-korux-tests" "User Commands"

.SH NAME
run-korux-tests \- Tool for automated testing of the Korux Gnu/Linux distribution.

.SH SYNOPSIS
\fBrun-korux-tests\fR

.SH DESCRIPTION
\fBrun-korux-tests\fR is a script for automated testing of the KoruX OS installation. It checks for the presence of required packages, files, directories, services, and their configurations, as well as other system parameters.

.SH OPTIONS
The script does not support command-line options. It should be run with superuser privileges.

.SH USAGE
To run the script, use the following command:
.IP
\fB$ sudo run-korux-tests\fR

.SH AUTHOR
Written by KoruX GNU/Linux.

.SH REPORTING BUGS
Report bugs at: <https://github.com/KoruX-Gnu-Linux/KoruX/issues>

.SH COPYRIGHT
Copyright: 2025, KoruX GNU/Linux <korux.dev@list.ru>
.br
License: GPL-3+
